import { v4 as uuidv4 } from "uuid";
function chillHop() {
	return [
		{
			name: "Beaver Creek",
			cover: require("./assets/covers/BeaverCreek.png"),
			artist: "Aso, Middle School, Aviino",
			audio: require("./assets/songs/Beaver Creek.mp3"),
			color: ["#205950", "#2ab3bf"],
			id: uuidv4(),
			active: true,
		},
		{
			name: "Daylight",
			cover: require("./assets/covers/Aiguille.jpg"),
			artist: "Aiguille",
			audio: require("./assets/songs/Daylight.mp3"),
			color: ["#EF8EA9", "#ab417f"],
			id: uuidv4(),
			active: false,
		},
		{
			name: "Keep Going",
			cover: require("./assets/covers/Sworn.jpg"),
			artist: "Swørn",
			audio: require("./assets/songs/Keep Going.mp3"),
			color: ["#CD607D", "#c94043"],
			id: uuidv4(),
			active: false,
		},
		{
			name: "Nightfall",
			cover: require("./assets/covers/NightFall.png"),
			artist: "Aiguille",
			audio: require("./assets/songs/Nightfall.mp3"),
			color: ["#EF8EA9", "#ab417f"],
			id: uuidv4(),
			active: false,
		},
		{
			name: "Reflection",
			cover: require("./assets/covers/Reflections.png"),
			artist: "Swørn",
			audio: require("./assets/songs/Reflection.mp3"),
			color: ["#CD607D", "#c94043"],
			id: uuidv4(),
			active: false,
		},
		{
			name: "Under the City Stars",
			cover: require("./assets/covers/CanaryForest.jpg"),
			artist: "Aso, Middle School, Aviino",
			audio: require("./assets/songs/Under the City Stars.mp3"),
			color: ["#205950", "#2ab3bf"],
			id: uuidv4(),
			active: false,
		},
		{
			name: "Adrenaline",
			cover: require("./assets/covers/Adrenaline.png"),
			artist: "Otherside",
			audio: require("./assets/songs/Adrenaline.mp3"),
			color: ["#EF8EA9", "#ab417f"],
			id: uuidv4(),
			active: false,
		},
		{
			name: "Outer Space",
			cover: require("./assets/covers/OuterSpace.png"),
			artist: "Flat Bread",
			audio: require("./assets/songs/Outer Space.mp3"),
			color: ["#CD607D", "#c94043"],
			id: uuidv4(),
			active: false,
		},
		{
			name: "Wind Down",
			cover: require("./assets/covers/WindDown.png"),
			artist: "Hammys",
			audio: require("./assets/songs/Wind Down.mp3"),
			color: ["#205950", "#2ab3bf"],
			id: uuidv4(),
			active: false,
		},
	];
}

export default chillHop;
